server:
  tomcat:
    connection-timeout: 25s
  forward-headers-strategy: framework
  error:
    include-message: always
  servlet:
    session:
      timeout: 30d
      cookie:
        max-age: 30d
merlin:
  azure:
    key: key
    url: url
  passwords:
    - Scarlet
    - Stellar
    - Whiskers
    - Lagoon
    - Harmony
    - Thunder
    - Willow
    - Blossom
    - Saffron
    - Velvet
    - Serene
    - Twilight
    - Mosaic
    - Breeze
    - Pebbles
    - Jade
    - Radiant
    - Glimmer
    - Flamingo
    - Nimbus
    - Marigold
    - Wander
    - Aurora
    - Luminary
    - Misty
    - Tropic
    - Ember
    - Enigma
    - Zephyr
    - Poppies
    - Mirage
    - Tundra
    - Quasar
    - Aquatic
    - Zinnia
    - Symphony
    - Glitter
    - Tranquilize
    - Bliss
    - Whisper
    - Coral
    - Opal
    - Cascade
    - Gossamer
    - Azure
    - Jubilee
    - Reverie
    - Solace
    - Elysian
    - Puzzle
    - Lemon
    - Helmet
    - Breeze
    - Ticket
    - Turtle
    - Wallet
    - Orange
    - Bakery
    - Circus
    - Hammer
    - Juggle
    - Zipper
    - Muffin
    - Cherry
    - Planet
    - Rocket
    - Father
    - Camera
    - Castle
    - Ginger
    - Basket
    - Forest
    - Dolphin
    - Friend
    - Guitar
    - Icebox
    - Jaguar
    - Lizard
    - Mosaic
    - Needle
    - Outlet
    - Pirate
    - Rabbit
    - Singer
    - Travel
    - Walnut
    - Window
    - Yellow
    - Anchor
    - Bumble
    - Candle
    - Dancer
    - Fabric
    - Goblet
    - Hammer
    - Insect
    - Jacket
    - Kitchen
    - Locket
    - Marvel
    - Nimble
    - Oyster
    - Parrot
    - Quiver
    - Racket
    - Saddle
    - Thumbs
    - Umbrella
    - Velvet
    - Waffle
    - Zenith
    - Banana
    - Basket
    - Circle
    - Doctor
    - Engine
    - Farmer
    - Guitar
    - Hiccup
    - Insect
    - Jigsaw
    - Kettle
    - Ladder
    - Market
    - Noodle
    - Pancake
    - Rabbit
    - Snakes
    - Tomato
    - Unicorn
    - Violet
    - Window
    - Yacht
    - Zebra
    - Breeze
    - Carpet
    - Dancer
    - Empire
    - Feather
    - Grapes
    - Helmet
    - Inning
    - Jacket
    - Kitten
    - Lizard
    - Mantis
    - Number
    - Outlet
    - Parrot
    - Quiver
    - Ransom
    - Saddle
    - Tangle
    - Uptake
    - Vortex
    - Wrench
    - Yellow
    - Zodiac
    - Bangle
    - Candle
    - Dimple
    - Eagle
    - Frugal
    - Garden
    - Hobbit
    - Icicle
    - Jungle
    - Kettle
    - Lively
    - Master
    - Nectar
    - Onyx
    - Pirate
    - Quiver
spring:
  session:
    store-type: memory
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus
